### ISSUE TITLE
Where is your code? 

### ISSUE THREAD

**Issue by Lextuga007** [johnmackintosh/pyramid-plots#2]
😄 we want to copy it.

**Comment by Analyst-In-The-Wild** [comment]
Love CDU Data Science Team ❤️

**Comment by johnmackintosh** [comment]
Thanks for your interest 👍 
do you want to wait for a more generic version, because there are a few assumptions about data structure etc, not least column names and values...?
I should have a more generalised version in the next few days

**Comment by Analyst-In-The-Wild** [comment]
Yeah we can probably cope waiting 😁  it is just so cool and beautiful anything that can help us create something similar for us would be greatly appreciated ❤️

**Comment by johnmackintosh** [comment]
@Lextuga007  @Analyst-In-The-Wild 
You should hopefully have something vaguely useful now c/o @Lextuga007

**Comment by johnmackintosh** [comment]
updated for latest (2021) data
